name: Testing github action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/cheeckout@v2
      - name: Set up JDK 11
        uses: action/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify